### ISSUE TITLE
Question about texture

### ISSUE THREAD

**Issue by Un1Lee** [ammar-n-abbas/FoundationPoseROS2#11]
Thank you for your help fro last question. But sorry, I have a new question.
The question is that foundation in isaac which need mesh and texture(if not, use no color). 
But your code only subs mesh, such as class code:class FoundationPose:
  def __init__(self, model_pts, model_normals, symmetry_tfs=None, mesh=None, scorer:ScorePredictor=None, refiner:PoseRefinePredictor=None, glctx=None, debug=0, debug_dir='/home/bowen/debug/novel_pose_debug/'):

There is no way for texture. I think it will be better with texture.
Can you tell me how to use texture in your code? 
If I change the code successfully( I want the code use texture when the path have jpg/png, and only use mesh when path has no jpg/png), I will push my code.

**Comment by ammar-n-abbas** [comment]
Sorry, I'm not familiar with this.
________________________________
From: Un1Lee ***@***.***>
Sent: Friday, December 20, 2024 9:02:12 AM
To: ammar-n-abbas/FoundationPoseROS2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ammar-n-abbas/FoundationPoseROS2] Question about texture (Issue #11)


Thank you for your help fro last question. But sorry, I have a new question.
The question is that foundation in isaac which need mesh and texture(if not, use no color).
But your code only subs mesh, such as class code:class FoundationPose:
def init(self, model_pts, model_normals, symmetry_tfs=None, mesh=None, scorer:ScorePredictor=None, refiner:PoseRefinePredictor=None, glctx=None, debug=0, debug_dir='/home/bowen/debug/novel_pose_debug/'):

There is no way for texture. I think it will be better with texture.
Can you tell me how to use texture in your code?
If I change the code successfully( I want the code use texture when the path have jpg/png, and only use mesh when path has no jpg/png), I will push my code.

**Comment by Un1Lee** [comment]
OK, I found that the origin sample data has offer mesh with its mtl and texture image. 
I check that mesh.load(path) will load the texture image when the mtl in obj file and the texture image is under the same dir.

>>> import trimesh
>>> mesh1 = trimesh.load('../textured_simple.obj') #without mtl and texutre image
>>> scene = trimesh.Scene(mesh1)
>>> scene.show() # do not have color
SceneViewer(width=1800, height=1350)
>>> mesh2 = trimesh.load('./textured_simple.obj') #with mtl and texutre image
>>> scene = trimesh.Scene(mesh2)
>>> scene.show() # have color

So I think that when load mesh, it will depend whether the mesh has texture or not.
We can know this in your code FoundationPoseROS2/FoundationPose/estimater.py/FoundationPose class->reset_object function->68-70 line.
if self.mesh is not None:
      self.mesh_path = f'/tmp/{uuid.uuid4()}.obj'
      self.mesh.export(self.mesh_path)
cd /tmp, and you will find a material.mtl and material_0.png(which is grey)
It means that we do not need any more code to load texture.
To load texture, we only need to add mtl and texture image under the same dir.

[https://github.com/NVlabs/FoundationPose/issues/193](FoundationPose texture question)
