### ISSUE TITLE
Case when the object is not in view

### ISSUE THREAD

**Issue by retazo0018** [ammar-n-abbas/FoundationPoseROS2#2]
Hi @ammar-n-abbas ,

Thanks for the great work!

Can it also handle cases where the desired object is not in view? If not, are there any pointers on how to handle these cases?

Thanks,

Best,

**Comment by ammar-n-abbas** [comment]
Hi @retazo0018 

Once the object is back in scene it can reattach the lost pose to it if it's closer to it. As the pose estimation is done only on the first frame, a good way to approach it would be to reinitiate pose estimation in such cases.

**Comment by retazo0018** [comment]
Thank you!
