### ISSUE TITLE
torch.cuda.OutOfMemoryError:

### ISSUE THREAD

**Issue by Muhayyuddin** [ammar-n-abbas/FoundationPoseROS2#4]
Hi, Thank you very much for your nice work. I successfully build FoundationPoseRos2 within a docker container, when I run the code it shows the selection window after selecting it also display the segmentation but when i select the cube in the segmented image, it generate an error of cuda outofMemory.  below are some screenshots of the execution and the error. any Idea to fix this issue thanks. 
![Screenshot from 2024-11-08 23-59-59](https://github.com/user-attachments/assets/275d126b-4059-4542-a356-ee96d0832645)
![Screenshot from 2024-11-09 00-00-16](https://github.com/user-attachments/assets/36948d17-27cd-4308-a9dc-7283e5c1756c)
![Screenshot from 2024-11-08 23-58-05](https://github.com/user-attachments/assets/c261f5e7-a372-421a-bce2-035001b931b8)

**Comment by ammar-n-abbas** [comment]
Do you have a 6GB GPU, it would be at least 8-16GB

**Comment by Muhayyuddin** [comment]
Oh ok thanks for highlighting the minimum GPU requirement issue. I will try with higher GPU thanks

**Comment by ammar-n-abbas** [comment]
Also, if you are using a custom model, make sure it's mesh is not too detailed and heavy.

**Comment by mcres** [comment]
I've experienced the same error (with a valid GPU). In my case, it helped lowering down both color and depth cameras resolution from `1280x720` to `848x480` to prevent the script from crashing.

I'd say the problem is the resolution, not so much the FPS. I guess that the reason is that images that are not processed are simply discarded, thus not adding computational load to the GPU.

@ammar-n-abbas do you have some intuition regarding maximum STL/OBJ file size allowed? Could you also illustrate what a _detailed_ mesh could be with an example?

**Comment by ammar-n-abbas** [comment]
There was a minor bug in the code which has been fixed now, apologies for that.
The demo data rosbag screen recording has now been added in the Readme along with the terminal log.

@Muhayyuddin can you test it out with your 6GB GPU?

**Comment by rassulz** [comment]
> I've experienced the same error (with a valid GPU). In my case, it helped lowering down both color and depth cameras resolution from `1280x720` to `848x480` to prevent the script from crashing.
> 
> I'd say the problem is the resolution, not so much the FPS. I guess that the reason is that images that are not processed are simply discarded, thus not adding computational load to the GPU.
> 
> [@ammar-n-abbas](https://github.com/ammar-n-abbas) do you have some intuition regarding maximum STL/OBJ file size allowed? Could you also illustrate what a _detailed_ mesh could be with an example?

Where and How did you changed resolution?
