### ISSUE TITLE
Provide rosbag for reproduction

### ISSUE THREAD

**Issue by mcres** [ammar-n-abbas/FoundationPoseROS2#6]
Like #3, I cannot detect the pose of a custom object.

It would be nice to reproduce the results presented [here](https://github.com/ammar-n-abbas/FoundationPoseROS2/blob/main/assets/tutorial.mp4) in my own setup, to make sure that there are no issues with dependencies or whatsoever.

Could you provide a rosbag with the color and depth images, and the camera info so that we can detect the objects defined in `demo_data/`? This way I could check that my pipeline has been built correctly.

**Comment by ammar-n-abbas** [comment]
Thank you for the suggestion.
The Readme is now updated with the rosbag demo

**Comment by mcres** [comment]
Thanks! I'm posting the command with the needed remappings for the default `/pose_estimation_node` subscription topics, in case someone is lost with that:

```bash
ros2 bag play cube_demo_data_rosbag2 --remap /camera/camera/aligned_depth_to_color/image_raw:=/camera/aligned_depth_to_color/image_raw /camera/camera/color/image_raw:=/camera/color/image_raw /camera/camera/color/camera_info:=/camera/color/camera_info
```

**Comment by mcres** [comment]
Unfortunately, I am not able to reproduce the pose estimation of the cube.

After running the `foundationpose_ros_multi.py` script and the rosbag, clicking on the cube and pressing `Enter` I get the following error:

```bash
[INFO] [1731527852.431736667] [pose_estimation_node]: Object 0 selected.
[reset_object()] self.diameter:0.1299038105676658, vox_size:0.006495190528383291
[reset_object()] self.pts:torch.Size([8, 3])
[reset_object()] reset done
[make_rotation_grid()] cam_in_obs:(42, 4, 4)
[make_rotation_grid()] rot_grid:(252, 4, 4)
num original candidates = 252
num of pose after clustering: 252
[make_rotation_grid()] after cluster, rot_grid:(252, 4, 4)
[make_rotation_grid()] self.rot_grid: torch.Size([252, 4, 4])
Traceback (most recent call last):
  File "/home/martinho/acceleration/foundation_pose_ws/src_2/FoundationPoseROS2/foundationpose_ros_multi.py", line 377, in <module>
    main()
  File "/home/martinho/acceleration/foundation_pose_ws/src_2/FoundationPoseROS2/foundationpose_ros_multi.py", line 372, in main
    rclpy.spin(node)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 739, in spin_once
    self._spin_once_impl(timeout_sec)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 736, in _spin_once_impl
    raise handler.exception()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 437, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 362, in _execute_subscription
    await await_or_execute(sub.callback, msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
    return callback(*args)
  File "/home/martinho/acceleration/foundation_pose_ws/src_2/FoundationPoseROS2/foundationpose_ros_multi.py", line 147, in depth_callback
    self.process_images()
  File "/home/martinho/acceleration/foundation_pose_ws/src_2/FoundationPoseROS2/foundationpose_ros_multi.py", line 294, in process_images
    self.meshes = [self.meshes[idx] for idx in selected_indices]
  File "/home/martinho/acceleration/foundation_pose_ws/src_2/FoundationPoseROS2/foundationpose_ros_multi.py", line 294, in <listcomp>
    self.meshes = [self.meshes[idx] for idx in selected_indices]
IndexError: list index out of range
```

If I comment the [lines](https://github.com/ammar-n-abbas/FoundationPoseROS2/blob/main/foundationpose_ros_multi.py#L294-L295) that cause the error (not sure why it is needed to set `self.meshes` and `self.bounds` at this point), I am able to not make it crash. However, no pose is detected as indicated in the images:

| Mask selection screen | Pose estimation screen :x: |
|-----------------------|------------------------|
| ![Screenshot from 2024-11-13 20-51-35](https://github.com/user-attachments/assets/4ac4952d-69e7-40ef-b0ad-769a3f6ddb77)                    | ![Screenshot from 2024-11-13 20-51-39](https://github.com/user-attachments/assets/7c41ac60-c91f-4d71-9604-b0b008bef10b)                     |

Here what it is logged on the terminal: [rosbag_reproduction_log.txt](https://github.com/user-attachments/files/17738651/rosbag_reproduction_log.txt)

**Comment by ammar-n-abbas** [comment]
@mcres can you check if the demo_data has the meshes stored in them and the file selector can read it? Can you show the file selector GUI as from the mesh selection GUI it says next object is "None" which should not be the case

**Comment by mcres** [comment]
@ammar-n-abbas that seems fine. Find below a video with the whole procedure: [foundation_pose_rosbag.webm](https://github.com/user-attachments/assets/6ced047c-352e-4823-b774-b3263321a7e2)

Some comments:
- I've moved the rest of the mesh files to another folder so it only takes `demo_data/cube/cube.obj` into account.
- `cube.obj` defines a cube of 7.5 cm length, which I suppose is OK. I can open the file, no issues with that.
- After I click on the cube, I hit `Enter` to start the pose estimation but nothing happens even if I let it run for a fair amount of time.

Could you perhaps share the output of your screen as well as the log of your console when you successfully reproduce the example so we can compare it?

**Comment by ammar-n-abbas** [comment]
There was a minor bug in the code which has been fixed now, apologies for that.
The demo data rosbag screen recording has now been added in the Readme along with the terminal log.

**Comment by ammar-n-abbas** [comment]
The file (foundationpose_ros_multi.py) has been modified and the repo now includes the modified lines in estimater.py please download it from this repo's last commit
